package com.thewhite.blank.api.skill;

import com.thewhite.blank.api.CollectionDto;
import com.thewhite.blank.api.skill.dto.*;
import com.thewhite.blank.api.skill.mapper.SkillMapper;
import com.thewhite.blank.model.Skill;
import com.thewhite.blank.service.skill.SkillService;
import com.thewhite.blank.service.skill.argument.SearchSkillArgument;
import com.thewhite.blank.service.skill.argument.UpdateSkillArgument;
import com.thewhite.blank.util.MapperUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.UUID;

import static org.springframework.http.HttpStatus.CREATED;


/**
 * Generated by Thanos
 */
@RestController
@RequestMapping("skill")
@RequiredArgsConstructor
public class SkillController {

    private final SkillService service;
    private final SkillMapper mapper;

    @PostMapping("create")
    @ResponseStatus(CREATED)
    public SkillDto create(@RequestBody @Valid CreateSkillDto dto) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(service::create)
                          .compose(mapper::toCreateArgument)
                          .apply(dto);
    }

    @GetMapping("{id}")
    public SkillDto get(@PathVariable UUID id) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(service::getExisting)
                          .apply(id);
    }

    @GetMapping("list")
    public List<SkillListDto> list(SearchSkillDto dto, Sort sort) {
        SearchSkillArgument argument = mapper.toSearchArgument(dto);

        List<Skill> list = service.list(argument, sort);

        return MapperUtils.mapList(mapper::toListDto, list);
    }

    @GetMapping("page")
    public CollectionDto<SkillListDto> page(SearchSkillDto dto, Pageable pageable) {
        SearchSkillArgument argument = mapper.toSearchArgument(dto);

        Page<Skill> page = service.page(argument, pageable);

        return MapperUtils.mapPage(mapper::toListDto, page);
    }

    @PostMapping("{id}/update")
    public SkillDto update(@PathVariable UUID id, @RequestBody @Valid UpdateSkillDto dto) {
        UpdateSkillArgument argument = mapper.toUpdateArgument(dto);

        Skill entity = service.update(id, argument);

        return mapper.toDto(entity);
    }

    @PostMapping("{id}/delete")
    public void delete(@PathVariable UUID id) {
        service.delete(id);
    }
}