package com.thewhite.blank.api.review;

import com.thewhite.blank.action.review.create.CreateReviewAction;
import com.thewhite.blank.action.review.update.UpdateReviewAction;
import com.thewhite.blank.action.review.update.UpdateReviewActionArgument;
import com.thewhite.blank.api.CollectionDto;
import com.thewhite.blank.api.review.dto.*;
import com.thewhite.blank.api.review.mapper.ReviewMapper;
import com.thewhite.blank.model.Review;
import com.thewhite.blank.service.review.ReviewService;
import com.thewhite.blank.service.review.argument.SearchReviewArgument;
import com.thewhite.blank.util.MapperUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.UUID;

import static org.springframework.http.HttpStatus.CREATED;


/**
 * Generated by Thanos
 */
@RestController
@RequestMapping("review")
@RequiredArgsConstructor
public class ReviewController {

    private final CreateReviewAction createReviewAction;
    private final UpdateReviewAction updateReviewAction;
    private final ReviewService service;
    private final ReviewMapper mapper;

    @PostMapping("create")
    @ResponseStatus(CREATED)
    public ReviewDto create(@RequestBody @Valid CreateReviewDto dto) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(createReviewAction::execute)
                          .compose(mapper::toCreateActionArgument)
                          .apply(dto);
    }

    @GetMapping("{id}")
    public ReviewDto get(@PathVariable UUID id) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(service::getExisting)
                          .apply(id);
    }

    @GetMapping("list")
    public List<ReviewListDto> list(SearchReviewDto dto, Sort sort) {
        SearchReviewArgument argument = mapper.toSearchArgument(dto);

        List<Review> list = service.list(argument, sort);

        return MapperUtils.mapList(mapper::toListDto, list);
    }

    @GetMapping("page")
    public CollectionDto<ReviewListDto> page(SearchReviewDto dto, Pageable pageable) {
        SearchReviewArgument argument = mapper.toSearchArgument(dto);

        Page<Review> page = service.page(argument, pageable);

        return MapperUtils.mapPage(mapper::toListDto, page);
    }

    @PostMapping("{id}/update")
    public ReviewDto update(@PathVariable UUID id, @RequestBody @Valid UpdateReviewDto dto) {
        UpdateReviewActionArgument argument = mapper.toUpdateActionArgument(id, dto);

        Review entity = updateReviewAction.execute(argument);

        return mapper.toDto(entity);
    }

    @PostMapping("{id}/delete")
    public void delete(@PathVariable UUID id) {
        service.delete(id);
    }
}