package com.thewhite.blank.action.review.update;

import lombok.Builder;
import lombok.Value;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateReviewActionArgument {

    UUID id;
    UUID userId;
    UUID exerciseId;
    String description;
}