package com.thewhite.blank.api.announcement.dto;

import lombok.*;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CreateAnnouncementDto {

    String title;
    UUID imageId;
    Long price;
    String description;
    UUID teacherId;
}