package com.thewhite.blank.service.exercise.argument;

import com.thewhite.blank.model.Announcement;
import com.thewhite.blank.model.User;
import lombok.Builder;
import lombok.Value;

import java.time.LocalDateTime;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateExerciseArgument {

    String title;

    String description;

    Announcement announcement;

    User teacher;

    User student;

    LocalDateTime date;

}
