package com.thewhite.blank.action.review.create;

import lombok.Builder;
import lombok.Value;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class CreateReviewActionArgument {

    UUID userId;
    UUID exerciseId;
    String description;
}