package com.thewhite.blank.action.exercise.update;

import lombok.Builder;
import lombok.Value;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateExerciseActionArgument {

    UUID id;
    String title;
    String description;
    UUID announcementId;
    UUID teacherId;
    UUID studentId;
    LocalDateTime date;
}