package com.thewhite.blank.service.announcement;

import com.thewhite.blank.model.Announcement;
import com.thewhite.blank.service.announcement.argument.CreateAnnouncementArgument;
import com.thewhite.blank.service.announcement.argument.SearchAnnouncementArgument;
import com.thewhite.blank.service.announcement.argument.UpdateAnnouncementArgument;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.util.List;
import java.util.Optional;
import java.util.UUID;


/**
 * Generated by Thanos
 */
public interface AnnouncementService {

    Announcement create(CreateAnnouncementArgument argument);

    Optional<Announcement> get(UUID id);

    Announcement getExisting(UUID id);

    List<Announcement> list(SearchAnnouncementArgument argument, Sort sort);

    Page<Announcement> page(SearchAnnouncementArgument argument, Pageable pageable);

    Announcement update(UUID id, UpdateAnnouncementArgument argument);

    void delete(UUID id);
}