package com.thewhite.blank.service.skill;

import com.thewhite.blank.model.Skill;
import com.thewhite.blank.service.skill.argument.CreateSkillArgument;
import com.thewhite.blank.service.skill.argument.SearchSkillArgument;
import com.thewhite.blank.service.skill.argument.UpdateSkillArgument;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.util.List;
import java.util.Optional;
import java.util.UUID;


/**
 * Generated by Thanos
 */
public interface SkillService {

    Skill create(CreateSkillArgument argument);

    Optional<Skill> get(UUID id);

    Skill getExisting(UUID id);

    List<Skill> list(SearchSkillArgument argument, Sort sort);

    Page<Skill> page(SearchSkillArgument argument, Pageable pageable);

    Skill update(UUID id, UpdateSkillArgument argument);

    void delete(UUID id);
}