package com.thewhite.blank.service.review;

import com.thewhite.blank.model.Review;
import com.thewhite.blank.service.review.argument.CreateReviewArgument;
import com.thewhite.blank.service.review.argument.SearchReviewArgument;
import com.thewhite.blank.service.review.argument.UpdateReviewArgument;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.util.List;
import java.util.Optional;
import java.util.UUID;


/**
 * Generated by Thanos
 */
public interface ReviewService {

    Review create(CreateReviewArgument argument);

    Optional<Review> get(UUID id);

    Review getExisting(UUID id);

    List<Review> list(SearchReviewArgument argument, Sort sort);

    Page<Review> page(SearchReviewArgument argument, Pageable pageable);

    Review update(UUID id, UpdateReviewArgument argument);

    void delete(UUID id);
}