package com.thewhite.blank.api.user.mapper;

import com.thewhite.blank.api.user.dto.*;
import com.thewhite.blank.model.Skill;
import com.thewhite.blank.model.User;
import com.thewhite.blank.service.user.argument.CreateUserArgument;
import com.thewhite.blank.service.user.argument.SearchUserArgument;
import com.thewhite.blank.service.user.argument.UpdateUserArgument;
import org.mapstruct.Mapper;

import java.util.List;


/**
 * Generated by Thanos
 */
@Mapper
public interface UserMapper {

    UserDto toDto(User entity);

    UserListDto toListDto(User entity);

    UpdateUserArgument toUpdateArgument(UpdateUserDto dto, List<Skill> learn, List<Skill> teach);

    SearchUserArgument toSearchArgument(SearchUserDto dto);

    CreateUserArgument toCreateArgument(CreateUserDto dto, List<Skill> learn, List<Skill> teach);
}