package com.thewhite.blank.service.review.argument;

import com.thewhite.blank.model.Exercise;
import com.thewhite.blank.model.User;
import lombok.Builder;
import lombok.Value;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateReviewArgument {

    User user;

    Exercise exercise;

    String description;

}
