package com.thewhite.blank.action.announcement.create;

import lombok.Builder;
import lombok.Value;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class CreateAnnouncementActionArgument {

    String title;
    UUID imageId;
    Long price;
    String description;
    UUID teacherId;
}