package com.thewhite.blank.api.exercise;

import com.thewhite.blank.action.exercise.create.CreateExerciseAction;
import com.thewhite.blank.action.exercise.update.UpdateExerciseAction;
import com.thewhite.blank.action.exercise.update.UpdateExerciseActionArgument;
import com.thewhite.blank.api.CollectionDto;
import com.thewhite.blank.api.exercise.dto.*;
import com.thewhite.blank.api.exercise.mapper.ExerciseMapper;
import com.thewhite.blank.model.Exercise;
import com.thewhite.blank.service.exercise.ExerciseService;
import com.thewhite.blank.service.exercise.argument.SearchExerciseArgument;
import com.thewhite.blank.util.MapperUtils;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.UUID;

import static org.springframework.http.HttpStatus.CREATED;


/**
 * Generated by Thanos
 */
@RestController
@RequestMapping("exercise")
@RequiredArgsConstructor
public class ExerciseController {

    private final CreateExerciseAction createExerciseAction;
    private final UpdateExerciseAction updateExerciseAction;
    private final ExerciseService service;
    private final ExerciseMapper mapper;

    @PostMapping("create")
    @ResponseStatus(CREATED)
    public ExerciseDto create(@RequestBody @Valid CreateExerciseDto dto) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(createExerciseAction::execute)
                          .compose(mapper::toCreateActionArgument)
                          .apply(dto);
    }

    @GetMapping("{id}")
    public ExerciseDto get(@PathVariable UUID id) {
        return MapperUtils.getMapper(mapper::toDto)
                          .compose(service::getExisting)
                          .apply(id);
    }

    @GetMapping("list")
    public List<ExerciseListDto> list(SearchExerciseDto dto, Sort sort) {
        SearchExerciseArgument argument = mapper.toSearchArgument(dto);

        List<Exercise> list = service.list(argument, sort);

        return MapperUtils.mapList(mapper::toListDto, list);
    }

    @GetMapping("page")
    public CollectionDto<ExerciseListDto> page(SearchExerciseDto dto, Pageable pageable) {
        SearchExerciseArgument argument = mapper.toSearchArgument(dto);

        Page<Exercise> page = service.page(argument, pageable);

        return MapperUtils.mapPage(mapper::toListDto, page);
    }

    @PostMapping("{id}/update")
    public ExerciseDto update(@PathVariable UUID id, @RequestBody @Valid UpdateExerciseDto dto) {
        UpdateExerciseActionArgument argument = mapper.toUpdateActionArgument(id, dto);

        Exercise entity = updateExerciseAction.execute(argument);

        return mapper.toDto(entity);
    }

    @PostMapping("{id}/delete")
    public void delete(@PathVariable UUID id) {
        service.delete(id);
    }
}