package com.thewhite.blank.service.skill.argument;

import lombok.Builder;
import lombok.Value;

import java.util.List;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class SearchSkillArgument {
    List<UUID> ids;
}
