package com.thewhite.blank.service.skill.argument;

import lombok.Builder;
import lombok.Value;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateSkillArgument {

    String name;

}
