package com.thewhite.blank.api.skill.dto;

import lombok.*;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UpdateSkillDto {

    String name;

}