package com.thewhite.blank.api.review.mapper;

import com.thewhite.blank.action.review.create.CreateReviewActionArgument;
import com.thewhite.blank.action.review.update.UpdateReviewActionArgument;
import com.thewhite.blank.api.review.dto.*;
import com.thewhite.blank.model.Review;
import com.thewhite.blank.service.review.argument.SearchReviewArgument;
import org.mapstruct.Mapper;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Mapper
public interface ReviewMapper {

    ReviewDto toDto(Review entity);

    ReviewListDto toListDto(Review entity);

    CreateReviewActionArgument toCreateActionArgument(CreateReviewDto dto);

    UpdateReviewActionArgument toUpdateActionArgument(UUID id, UpdateReviewDto dto);

    SearchReviewArgument toSearchArgument(SearchReviewDto dto);
}