package com.thewhite.blank.model;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.util.UUID;

import static javax.persistence.EnumType.STRING;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Announcement extends BaseEntity {

    String title;

    UUID imageId;

    Long price;

    String description;

    @JoinColumn
    @ManyToOne
    User teacher;

    @Enumerated(value = STRING)
    AnnouncementStatus status;
}