package com.thewhite.blank.model;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.time.LocalDateTime;

import static javax.persistence.EnumType.STRING;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Exercise extends BaseEntity {

    String title;

    String description;

    @JoinColumn
    @ManyToOne
    Announcement announcement;

    @JoinColumn
    @ManyToOne
    User teacher;

    @JoinColumn
    @ManyToOne
    User student;

    LocalDateTime date;

    @Enumerated(value = STRING)
    ExerciseStatus status;
}