package com.thewhite.blank.model;

import lombok.*;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Review extends BaseEntity {

    @JoinColumn
    @ManyToOne
    User user;

    @JoinColumn
    @ManyToOne
    Exercise exercise;

    String description;
}