package com.thewhite.blank.model;

import lombok.*;

import javax.persistence.Entity;


/**
 * Generated by Thanos
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Skill extends BaseEntity {

    String name;
}