package com.thewhite.blank.service.user.argument;

import com.thewhite.blank.model.Skill;
import lombok.Builder;
import lombok.Value;

import java.util.List;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class CreateUserArgument {

    String nickname;

    String password;

    String displayName;

    String phone;

    Long balanceOnWallet;

    UUID avatarId;

    String description;

    List<Skill> learn;

    List<Skill> teach;

}