package com.thewhite.blank.api.user.dto;

import lombok.*;

import java.util.List;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CreateUserDto {

    String nickname;
    String password;
    String displayName;
    String phone;
    Long balanceOnWallet;
    UUID avatarId;
    String description;
    List<UUID> learnIds;
    List<UUID> teachIds;
}