package com.thewhite.blank.api.user.dto;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@NoArgsConstructor
public class SearchUserDto {

}