package com.thewhite.blank.api.user.dto;

import com.thewhite.blank.api.skill.dto.SkillDto;
import com.thewhite.blank.model.Skill;
import lombok.*;

import java.util.List;
import java.util.UUID;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserListDto {


    UUID id;

    String nickname;

    String password;

    String displayName;

    String phone;

    Long balanceOnWallet;

    UUID avatarId;

    String description;

    List<SkillDto> learn;

    List<SkillDto> teach;

}