package com.thewhite.blank.repository;

import com.thewhite.blank.model.Announcement;


/**
 * Generated by Thanos
 */
public interface AnnouncementRepository extends EntityRepository<Announcement> {
}