package com.thewhite.blank.api.announcement.mapper;

import com.thewhite.blank.action.announcement.create.CreateAnnouncementActionArgument;
import com.thewhite.blank.action.announcement.update.UpdateAnnouncementActionArgument;
import com.thewhite.blank.api.announcement.dto.*;
import com.thewhite.blank.model.Announcement;
import com.thewhite.blank.service.announcement.argument.SearchAnnouncementArgument;
import org.mapstruct.Mapper;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Mapper
public interface AnnouncementMapper {

    AnnouncementDto toDto(Announcement entity);

    AnnouncementListDto toListDto(Announcement entity);

    CreateAnnouncementActionArgument toCreateActionArgument(CreateAnnouncementDto dto);

    UpdateAnnouncementActionArgument toUpdateActionArgument(UUID id, UpdateAnnouncementDto dto);

    SearchAnnouncementArgument toSearchArgument(SearchAnnouncementDto dto);
}