package com.thewhite.blank.action.announcement.update;

import lombok.Builder;
import lombok.Value;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Value
@Builder
public class UpdateAnnouncementActionArgument {

    UUID id;
    String title;
    UUID imageId;
    Long price;
    String description;
    UUID teacherId;
}