package com.thewhite.blank.api.skill.mapper;

import com.thewhite.blank.api.skill.dto.*;
import com.thewhite.blank.model.Skill;
import com.thewhite.blank.service.skill.argument.CreateSkillArgument;
import com.thewhite.blank.service.skill.argument.SearchSkillArgument;
import com.thewhite.blank.service.skill.argument.UpdateSkillArgument;
import org.mapstruct.Mapper;


/**
 * Generated by Thanos
 */
@Mapper
public interface SkillMapper {

    SkillDto toDto(Skill entity);

    SkillListDto toListDto(Skill entity);

    CreateSkillArgument toCreateArgument(CreateSkillDto dto);

    UpdateSkillArgument toUpdateArgument(UpdateSkillDto dto);

    SearchSkillArgument toSearchArgument(SearchSkillDto dto);
}