package com.thewhite.blank.api.review.dto;

import lombok.*;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CreateReviewDto {

    UUID userId;
    UUID exerciseId;
    String description;
}