package com.thewhite.blank.api.review.dto;

import lombok.*;

import java.util.UUID;


/**
 * Generated by Thanos
 */
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UpdateReviewDto {

    UUID userId;

    UUID exerciseId;

    String description;

}